[project]
name = "gwas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy==2.2.5",
    "pandas==2.3.3",
    "scipy<1.16",
    "statsmodels==0.14.4",
]
